apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-prod
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:367521002816:certificate/3d834c70-5e5f-4d51-aa43-4e1c5b688ac6
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true
    alb.ingress.kubernetes.io/subnets: subnet-05f290860bc79af65,subnet-076547ed1e0c6316e,subnet-0d23241af3187d28f
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health

spec:
  ingressClassName: alb
  tls:
    - hosts:
        - orderservice.ebs.ng
        - inventoryservice.ebs.ng
        - paymentservice.ebs.ng
        - notificationservice.ebs.ng
      secretName: dummy-tls-secret
  rules:
    - host: orderservice.ebs.ng
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: usevkycservice
              port:
                number: 80
    - host: inventoryservice.ebs.ng
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backoffice
                port:
                  number: 80
    - host: paymentservice.ebs.ng
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontoffice
                port:
                  number: 80
    - host: notificationservice.ebs.ng
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: game
                port:
                  number: 80
